sudo: required

language: python

python:
- '2.7'

before_install:
- sudo apt-get -y update || true
- sudo apt-get install -y libdb5.3
install:
- dev/setup_venv.sh

script:
- ./integration_tests.sh

notifications:
  hipchat:
    rooms:
      secure: Awlmuv9iZG41jwzCYCqfaf3pNzjFjI5iSCVsq4NG8zFLDCrBdxqBUeGcCTnUBLrGHwtxuiZX08J/lh6BBi2M/eJiFQq2caLrEQ/Ml0GMqHOdlyzOZ54ib0eW7ydWdXMWD3jGyYRNI6DKhED1VKp6kFxbq4T9432N5+IynZ6nirK1Dj6Mg0kr4nLSPMPtRx0c/6HS0kqTQLIZidqtmVqLTzFHf7yV8cqJDUFRRdKmRdzmIkfx4bQzPP/WV4w339YtUfMfZ1RnRp/Cg4Yd5nO03/a+maboA7ZkcOgKTPtbrj/GKhiAD1/XmtaIeoMG9QausHTKhBtpBiI/+LOZU8D/5o1ma9Y0PddQm3obAaVuVk1farieCJK22wMy6DPqYZAmnAD/oq1Z3LkVYHb3T/X9KIFM0cGERSNZ9CX020l1OPHNkM8BdhFrRxU9ncq90imrH9QoezrI8xwry4ywNIkQHdsKqaruWsBm6SKZl4Gvcy9Z0p31zWWKn+HJ3UbnAImlIXC/o+XXRLjCGudAL4ohGiP+t5GYCv5//6bfs0ghQqE1xzZnNI/IFR3izanT15Iw3f6hgYeXZXROenV+p0siAXnMPHIqE6R6KD0RmKlz7xrQt4GoEvuasKSPdfHE/Ih5Qk5KhY34usI6BUS9j28aqhMrfwcKcR/E4h2c9B7mhvk=
