sudo: required

services:
- docker

language: python

python:
- '2.7'

# safelist branch to build
branches:
  only:
      - master

before_install:
- sudo apt-get -y update || true

install:
- dev/setup_venv.sh

script:
- echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
- dev/all_tests.sh
- docker logout

notifications:
  email:
    - bifer@alea-soluciones.com
