sudo: required

services:
  - docker
  
language: python

python:
  - "2.6"
  - "2.7"

install:
  - python setup.py develop
  - pip install -r requirements.txt  -r requirements-dev.txt

script:
  - ./integration_tests.sh
  

