sudo: required

services:
  - docker
  
language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
before_install:
  - sudo apt-get -y update
  - sudo apt-get -o DPkg::options::=--force-confmiss -y --force-yes install docker-engine

install:
  - python setup.py develop
  - pip install -r requirements.txt  -r requirements-dev.txt

script:
  - ./integration_tests.sh
  

